### ISSUE TITLE
Corpus filename is invalid under Windows

### ISSUE THREAD

**Issue by Chocobo1** [chewing/fuzzing-corpus#1]
### Background
I was trying to build `windows-chewing-tsf` under Windows and I usually check out the whole project tree with the command `git submodule update --init --remote --recursive`. The problem is that when recursively cloning `libchewing` it will check out the `fuzzing-corpus` submodule and it will fail here. This is due to reserved characters used in filenames.

### Problem
For example, this file `id:000000,time:0,execs:0,orig:id:003773,src:002317,time:3264222,execs:312390,op:havoc,rep:4` have reserved character `:`. The Windows have a list of reserved characters which cannot be used for filenames: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

### Solutions
1. I tweak my build script to skip over `fuzzing-corpus` repo manually.
  It is not a big problem for me but it adds a bit technical debt on my side. Besides, other developers (on Windows) might encounter the same issue so I wouldn't recommend it.
2. Swap the invalid character with something else. I couldn't really give a good replacement char here. The `:` looks nice for its purpose. Maybe you would have better ideas.

**Comment by kanru** [comment]
I think I'll just remove the submodule. It's not required for the fuzzer to work, and it's currently version specific.
